channels:
  - anaconda
  - conda-forge
  - bioconda
  - sagrudd
dependencies:
  - snakemake-minimal
  - conda-forge:jupyterlab
  - selenium
  - phantomjs
  - papermill
  - anaconda:python
  - anaconda:cython
  - anaconda:numpy
  - anaconda:scipy 
  - anaconda:scikit-learn
  - anaconda:numexpr
  - anaconda:mkl
  - anaconda:spyder
  - pip
  - pip:
    - "--editable=git+https://github.com/sagrudd/megrim.git#egg=megrim"
