channels:
  - conda-forge
  - bioconda
  - sagrudd
dependencies:
  - snakemake-minimal
  - jupyterlab
  - selenium
  - phantomjs
  - papermill
  - python
  - cython
  - numpy
  - scipy
  - pandas
  - spyder
  - nb_conda_kernels
  - bokeh
  - pip
  - pip:
    - "--editable=git+https://github.com/sagrudd/megrim.git#egg=megrim"
